# Generated by Django 4.2.1 on 2023-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensagem", models.TextField()),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
