# Generated by Django 4.2.1 on 2023-09-05 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="data_envio",
            new_name="CreatedAt",
        ),
    ]
